const $=id=>document.getElementById(id);const canvas=$('chart'),ctx=canvas.getContext('2d'),wrap=$('chartwrap');
const S={symbol:'EUR/USD',tf:'15m',candles:[],signal:null,price:null,zoom:1,offset:0,cross:true,mouse:{x:0,y:0},drag:false,lastX:0,paper:{balance:10000,position:null},watch:{}};
const symbols=['EUR/USD','GBP/USD','USD/JPY','AUD/USD','USD/CAD'];
const fmt=p=>Number.isFinite(+p)?(+p).toFixed(Math.abs(+p)>=20?3:5):'—';
async function api(symbol=S.symbol,tf=S.tf){const r=await fetch(`/api/signal?symbol=${encodeURIComponent(symbol)}&timeframe=${encodeURIComponent(tf)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.message||j.error||`HTTP ${r.status}`);return j}
function normalize(j){return(j.candles||[]).map((c,i)=>({time:c.time??c.datetime??i,open:+c.open,high:+c.high,low:+c.low,close:+c.close})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite))}
async function load(){ $('status').textContent='Loading…';try{const j=await api();S.candles=normalize(j);S.signal=j;S.price=Number(j.price??S.candles.at(-1)?.close);renderSignal(j);renderLegend();draw();$('status').textContent=`${j.source||'market'} · ${new Date().toLocaleTimeString()}`;updateWatch()}catch(e){$('status').textContent=`Data error: ${e.message}`}}
function renderLegend(){const c=S.candles.at(-1);if(!c)return;$('legend').innerHTML=`<div class="title">${S.symbol} · ${S.tf}</div><div class="ohlc">O ${fmt(c.open)} H ${fmt(c.high)} L ${fmt(c.low)} C ${fmt(c.close)}</div>`;$('quote').textContent=fmt(S.price);const p=S.candles.at(-2)?.close??S.price,pct=p?((S.price-p)/p*100):0;$('chg').textContent=`${pct>=0?'+':''}${pct.toFixed(2)}%`;$('chg').className=pct>=0?'chg up':'chg down'}
function renderSignal(j){const s=j.signal||j.direction||'WAIT';$('sig').textContent=s;$('sig').className=`signal ${s==='LONG'?'up':s==='SHORT'?'down':''}`;$('state').textContent=j.state||'—';$('structure').textContent=j.structure_bias||'—';$('breakout').textContent=j.breakout_state||'—';$('score').textContent=j.score==null?'—':j.score;$('reason').textContent=j.reason||'No strategy explanation'}
async function updateWatch(){for(const sym of symbols){try{const j=await api(sym,S.tf),p=Number(j.price??j.candles?.at(-1)?.close),q=Number(j.candles?.at(-2)?.close??p);S.watch[sym]={price:p,pct:q?((p-q)/q*100):0}}catch{}}renderWatch()}
function renderWatch(){const box=$('watch');box.innerHTML=symbols.map(sym=>{const x=S.watch[sym]||{},pct=x.pct??0;return `<button class="row" data-symbol="${sym}"><span><span class="sym">${sym}</span><small>Forex</small></span><span>${fmt(x.price)}</span><span class="${pct>=0?'up':'down'}">${pct>=0?'+':''}${pct.toFixed(2)}%</span></button>`}).join('');box.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{S.symbol=b.dataset.symbol;$('symbol').value=S.symbol;load()})}
function resize(){const r=wrap.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function visible(){const n=Math.max(30,Math.min(S.candles.length,Math.floor(105/S.zoom))),end=Math.max(n,S.candles.length-S.offset);return S.candles.slice(Math.max(0,end-n),end)}
function draw(){const r=wrap.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const data=visible();if(!data.length)return;const L=8,R=74,T=42,B=26,gw=w-L-R,gh=h-T-B;let lo=Math.min(...data.map(c=>c.low)),hi=Math.max(...data.map(c=>c.high));if(S.signal?.zone){lo=Math.min(lo,+S.signal.zone.low);hi=Math.max(hi,+S.signal.zone.high)}const pad=(hi-lo)*.08||.001;lo-=pad;hi+=pad;const y=p=>T+(hi-p)/(hi-lo)*gh,step=gw/data.length,cw=Math.max(2,step*.62);ctx.strokeStyle='#20262d';ctx.fillStyle='#707a86';ctx.font='10px Arial';for(let i=0;i<=6;i++){const yy=T+gh*i/6;ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(w-R,yy);ctx.stroke();ctx.fillText((hi-(hi-lo)*i/6).toFixed(Math.abs(hi)>=20?2:5),w-R+6,yy+3)}data.forEach((c,i)=>{const x=L+step*i+step/2,u=c.close>=c.open;ctx.strokeStyle=u?'#26a69a':'#ef5350';ctx.beginPath();ctx.moveTo(x,y(c.high));ctx.lineTo(x,y(c.low));ctx.stroke();ctx.fillStyle=u?'#26a69a':'#ef5350';const a=y(Math.max(c.open,c.close)),b=y(Math.min(c.open,c.close));ctx.fillRect(x-cw/2,a,cw,Math.max(1,b-a))});if(S.signal?.zone){const a=y(+S.signal.zone.high),b=y(+S.signal.zone.low);ctx.fillStyle='#2962ff16';ctx.fillRect(L,a,gw,b-a);ctx.strokeStyle='#2962ff66';ctx.strokeRect(L,a,gw,b-a)}if(Number.isFinite(S.price)){ctx.strokeStyle='#d8a84e';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(L,y(S.price));ctx.lineTo(w-R,y(S.price));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d8a84e';ctx.fillRect(w-R,y(S.price)-9,R,18);ctx.fillStyle='#0b0e11';ctx.fillText(fmt(S.price),w-R+5,y(S.price)+3)}if(S.signal?.entry_reference)drawLine(+S.signal.entry_reference,'#4fc3f7','ENTRY',L,R,y);if(S.signal?.stop_reference)drawLine(+S.signal.stop_reference,'#ef5350','SL',L,R,y);if(S.cross&&S.mouse.x>0){ctx.strokeStyle='#7b879455';ctx.beginPath();ctx.moveTo(S.mouse.x,T);ctx.lineTo(S.mouse.x,T+gh);ctx.moveTo(L,S.mouse.y);ctx.lineTo(w-R,S.mouse.y);ctx.stroke()}}
function drawLine(p,c,label,L,R,y){const yy=y(p);ctx.strokeStyle=c;ctx.setLineDash([6,4]);ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(w-R,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=c;ctx.fillText(label,L+5,yy-4)}
function tf(t){S.tf=t;S.offset=0;document.querySelectorAll('[data-tf]').forEach(b=>b.classList.toggle('active',b.dataset.tf===t));load()}
canvas.addEventListener('pointerdown',e=>{S.drag=true;S.lastX=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>S.drag=false);canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();S.mouse.x=e.clientX-r.left;S.mouse.y=e.clientY-r.top;if(S.drag){S.offset=Math.max(0,S.offset+Math.round((S.lastX-e.clientX)/6));S.lastX=e.clientX}draw()});canvas.addEventListener('wheel',e=>{e.preventDefault();S.zoom=Math.max(.55,Math.min(4,S.zoom+(e.deltaY<0?.12:-.12)));draw()},{passive:false});
$('symbol').onchange=e=>{S.symbol=e.target.value;load()};$('tf').onchange=e=>tf(e.target.value);$('refresh').onclick=load;$('fit').onclick=()=>{S.zoom=1;S.offset=0;draw()};$('cross').onclick=()=>{S.cross=!S.cross;draw()};$('mobile').onclick=()=>$('right').classList.toggle('open');$('reset').onclick=()=>{S.zoom=1;S.offset=0;draw()};document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>tf(b.dataset.tf));
$('buy').onclick=()=>openPaper('LONG');$('sell').onclick=()=>openPaper('SHORT');$('close').onclick=closePaper;function openPaper(side){if(S.paper.position||!Number.isFinite(S.price))return;const qty=Math.max(1,Number($('qty').value)||1000),sl=Number($('sl').value)||null,tp=Number($('tp').value)||null;S.paper.position={side,qty,entry:S.price,sl,tp};renderPaper()}function closePaper(){const p=S.paper.position;if(!p)return;S.paper.balance+=(S.price-p.entry)*(p.side==='LONG'?1:-1)*p.qty;S.paper.position=null;renderPaper()}function renderPaper(){const p=S.paper.position,pnl=p?(S.price-p.entry)*(p.side==='LONG'?1:-1)*p.qty:0;$('balance').textContent=S.paper.balance.toFixed(2);$('equity').textContent=(S.paper.balance+pnl).toFixed(2);$('pos').textContent=p?`${p.side} ${p.qty}`:'FLAT';$('entry').textContent=p?fmt(p.entry):'—';$('pnl').textContent=(pnl>=0?'+':'')+pnl.toFixed(2);$('close').disabled=!p;$('buy').disabled=!!p;$('sell').disabled=!!p}
window.addEventListener('resize',resize);resize();load();setInterval(load,30000);setInterval(()=>{renderPaper();draw()},1000);